### ISSUE TITLE
Build backend

### ISSUE THREAD

**Issue by ThomasWharton** [ThomasWharton/frag-tube#27]
Build complete backend using django rest frameworks

**Comment by ThomasWharton** [comment]
- [x] Issue 54 - Install django and other dependencies
- [x] Issue 57 - Add profiles app
- [x] Issue 56 - Build Profiles model
- [x] Issue 58 - Create SuperUser
- [x] Issue 59 - Install django rest framework
- [x] Issue 60 - Create profile views in drf
- [x] Issue 61 - Create profile url in drf
- [x] Issue 62 - Add profile serializer in drf
